grpc:
  client:
#    grpc-server:
#      address: 'static://127.0.0.1:6575'
#      negotiation-type: plaintext
    GLOBAL:
      negotiation-type: plaintext

spring:
  application:
    name: grpc-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8081