server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2_flowable;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: h2
    password: h2
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false